// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import AdministratorLayout from '~app/administrator.../layout'
import Administrator from '~app/administrator.../page'
import Skills from '~app/administrator.../skills/page'

import NotFound from '~components/common/NotFound'

function AdministratorSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<AdministratorLayout><Outlet /></AdministratorLayout>}
      >
        <Route
          index
          element={<Administrator />}
        />
        <Route
          path="skills"
          element={<Outlet />}
        >
          <Route
            index
            element={<Skills />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default AdministratorSubRouter
